### ISSUE TITLE
Allocation between boats (Bethany observes)

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/Survey-Planning#27]

**Comment by Ned-Laman-NOAA** [comment]
Once we get passed the first pre-cruise meeting (3/15) we will begin assigning projects to vessels. Many of the projects will be on both vessels, a few will be on one boat or the other-some of those bear discussion with the vessels before assigning them.

**Comment by Conrathcl** [comment]
I took a quick first stab at the allocation between boats [here](https://docs.google.com/spreadsheets/d/1br8esdbZYswRgeTI5EKr7PIXhePW4nCW/edit?usp=sharing&ouid=105279028397081025832&rtpof=true&sd=true).

My preliminary thought process:
Most projects can go on both vessels, particularly those with rare species.
I put the freezer heavy projects on the AK Provider  (Observer + Wells)
To balance that out a bit I put the large genetics project on Vessel 2 (Spies)
I put the sponge project on Sean's vessel (negotiable)

**Comment by Ned-Laman-NOAA** [comment]
I have no objections to this allocation. Good job, Christina!

**Comment by Ned-Laman-NOAA** [comment]
Hi all. Duane and I requested that the stomach lab reduce their collections this summer since they have professed an inability to process the samples that they already have on hand. They have responded and reduced the number of stomachs to be collected on AI 2022. Yay! See attached
[2022 AI Stomach Sampling plan_REDUCED_n.pdf](https://github.com/afsc-gap-products/Survey-Planning/files/8411730/2022.AI.Stomach.Sampling.plan_REDUCED_n.pdf)
.

**Comment by Ned-Laman-NOAA** [comment]
Quick update here. Stomach lab did reduce their collection request this year. Yay!
