### ISSUE TITLE
Food Habits request review

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/Survey-Planning#30]

**Comment by smcdermo** [comment]
HI Sarah,
I don't know how to start this project.  Do you know where we are getting the stomach request so we can look at them?

**Comment by SarahFriedman-NOAA** [comment]
Is there anything else we need to do for this task? Just a head's up that I will be on leave from this Friday until after the deadline for this task (March 14). If there is anything else that needs to be done I'm happy to get to it this week.

**Comment by Ned-Laman-NOAA** [comment]
Hi stomach collections team.
Find the CORE stomach collections request [here](https://docs.google.com/spreadsheets/d/1W8bKigNipl5IdQIQH5Kyq4twJxZKLi1zeS9UNE_JAsU/edit?usp=sharing).
Check in with Nancy Roberson to see if there is anything pending that's come across her desk. I haven't heard anything on my side.
Your basic responsibilities here are to let the stomach lab know that you're the point of contact with the survey group if they need one and to support their request as needed. The stomach lab is pretty self contained and generally doesn't need a lot of help with this request beyond us supplying stomach collectors on the boats. You will also be the point of contact to connect stomach collectors with the stomach lab for their training on collections.
Today I will be releasing the station allocation for general use . I will cc Rick H in the stomach lab when I do since they are waiting on this information to finalize their sampling plan.

**Comment by Ned-Laman-NOAA** [comment]
The team completed this review in March
