### ISSUE TITLE
Putting together document

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/Survey-Planning#38]

**Comment by Conrathcl** [comment]
Draft document  started.  Located in the G drive in the Aleutian folder, 2022, Ops plan.  I don't anticipate making much progress until a few more of the pieces fall in place: special projects, vessel 2, survey staffing is shared, core projects (suspect those are around somewhere, just need to track them down).   I think all of those items are quite close though, so we should be able to get into this a bit more soon. Feel free to review, edit, etc.

**Comment by MargaretSiple-NOAA** [comment]
@Conrathcl Does it make sense for Sarah or I to edit anything here? I can use track changes to put in some of the revisions/comments I had from the GOA survey, but was not planning on doing anything for this one until we get dates/2nd vessel.

**Comment by Ned-Laman-NOAA** [comment]
@MargaretSiple-NOAA @SarahFriedman-NOAA 
You can spectate on this. I'm hoping one of you can take the lead next year on this document and, as I think I mentioned already Megsie, I wanted to assign you to anything with a document this year just so that you are aware of the documents that may lend themselves to automation in the future
As is, I think we're at a point where I should find out who/where this document goes next; I'm on it.

**Comment by Ned-Laman-NOAA** [comment]
@MargaretSiple-NOAA @SarahFriedman-NOAA
Oops. I was thinking Cruise Announcement when I wrote the above. Everything there still applies, except that the Ops Manual doesn't go somewhere next. The Ops Manual is our guide and history for what happens each summer.
That said, if Christina needs some help with the Ops Manual she can reach out to the team assigned here as needed.

**Comment by MargaretSiple-NOAA** [comment]
Sounds good. I added some edits to the version on the G Drive using track changes. Not sure who we should be checking with to update the Minimum Attempted ID List (Table 1). Other things I think are all stuff that needs updating based on other moving pieces (staffing, vessels, etc).

**Comment by Ned-Laman-NOAA** [comment]
Typically the Minimum Attempted ID List will be updated by our taxonomist (@SarahFriedman-NOAA). I think if Sarah can consult with Duane this year to see if there need to be any changes to this list. There may also be some changes coming in the Porifera and @SeanRooney-NOAA will be beginning that conversation with Duane and Sarah soon.

**Comment by SarahFriedman-NOAA** [comment]
@Ned-Laman-NOAA I just chatted with Duane about this and there were three particular things he mentioned that I was hoping to get your thoughts on:
 - Sponges are being IDed to morphotype but we have no associated species codes with the different morphotypes, so perhaps it would be best to keep this as Porifera unid. 
 - For EBS at least, Duane recommended making shrimps identifiable to genus and hermit crabs to species, but he was unsure to what extend this framework lent itself to the sorts of species we encounter in the AI

**Comment by Ned-Laman-NOAA** [comment]
Thanks, Sarah.
Historically we have variety of sponges that we've ID'd to species, we have 4 species codes for morphotypes, and then what's left gets Porifera unid. As a minimum ID, Porifera unid. makes sense to me.
[Sponge_Morphotypes.pdf](https://github.com/afsc-gap-products/Survey-Planning/files/8257454/Sponge_Morphotypes.pdf)
I believe that Sean Rooney has recently determined that our ID success at the species level in the field isn't great and has found some new species to boot! Probably a discussion for another time though. 
I like the minimum shrimp ID to genus and hermit crabs to species. We have a good hermit crab guide and a few people who are really good with shrimps, but more who aren't. That seems a good fit to me.

**Comment by SarahFriedman-NOAA** [comment]
Ok, thanks for the feedback. That all sounds good to me.

**Comment by Conrathcl** [comment]
Hi All - this is what I have left to do and there are a few things I could use some help with:  

Ned can you:  Confirm daily email contact list: Michael, Ned, Jerry, and Nate?  Pg:  6

Update vessel contact information for both boats Pg. 135 (Ned do you have this information?)

Update personnel table – Nate will update Pg. 133

Update participant contact information Pg. 134 - I think we should consider whether this is appropriate for this document or if this information should be housed somewhere else that is more private but accessible if needed?  If we do decide to include it, my understanding from past Ops plans is that since people's phone numbers etc. are involved it will need to be filled out by Ned. 

Emergency contact table/flow chart needs to be replaced Pg. 136  This table as is doesn't look editable - I will see if I can find a more current version if one is out there or I can remake it if need be.  If anyone knows off the top of there head where to find..let me know. 

Items to review. These additions are the only substantive change that I've made this year. 
1. New CTD information has been added – input. Pg. 26  (very general with a reference to the more detailed instructions)
2. Input on station dropping wording. Pg. 19  (probably overly specific)

Feel free to review anything else as well.

I haven't had time to track down a particularly good cover photo - if anyone has one they want to use, feel free to replace. 

Fix table of contents when all of the above is completed

**Comment by Ned-Laman-NOAA** [comment]
Thanks, Christina.
Daily email list confirmed. Vessel contact info:
Vessel: F/V Alaska Provider
Vessel Design: Pacific Trawler
Call sign: WDG2215
Vessel registration number: 
Home Port: Seattle

Vessel Owner: US Seafoods
Address: 1801 Fairview Avenue East, Suite 100; Seattle, WA 98102
Phone: 206-763-3133
Fax: 206-832-1695
Contact: Matt Upton
Alternate Contact: 
Captain: Loren Reynolds

Vessel: F/V Ocean Explorer
Vessel Design: Pacific Trawler
Call sign: WCZ9006
Vessel registration number: 678236
Home Port: Seattle

Vessel Owner: B & N Fisheries
Address:   303 NE Northlake Way, Seattle, WA 98105
Phone: 206-553-9123; 206-783-1948
Fax:  
Contact: Jerry Downing
Alternate Contact: Cassie Owens
Captain: Dan Carney

I think contact information for participants belongs in a different place, like a separate spreadsheet that doesn't have the longevity of the Ops Manual.

Emergency contact and flow sheet was recently updated by Liz Dawson so check with her for that.

I will make some time to look at language for CTD and station dropping tomorrow. @Conrathcl share the link for the document here please?

**Comment by MargaretSiple-NOAA** [comment]
Hi Ned et al. -- if you need it, I have contact info for participants stored [here](https://docs.google.com/spreadsheets/d/1hsG8rBmBmUyAGX_yVisE1mo7R7HRmdC_uvR9GWDAjnw/edit?usp=sharing) in the "staff summary" tab. Since it's personal contact info I will leave it to Ned to codify it into any actual documents.

**Comment by Ned-Laman-NOAA** [comment]
This is great, Megsie. My recc will be that once this is full we provide it to all travelers so that they can contact each other en route if necessary. Probably just as this worksheet but preface the distribution with an ask for people to indicate if they would prefer to not have that information shared. Does that sound like a reasonable approach?

**Comment by Conrathcl** [comment]
Thanks Ned!  The current document is living on the G drive: Aleutians/ 2022/Ops Plan and it is beyond my current GIT skills to know how to link that here.  I copied it to the google drive [here](https://docs.google.com/document/d/1_N8J36A47Iep1GeCePmnNZTPjH5lLEcx/edit?usp=sharing&ouid=105279028397081025832&rtpof=true&sd=true).  It may make more sense to just have it as a google doc?  If so I will remove the G drive copy so we don't end up with multiple versions.

**Comment by Ned-Laman-NOAA** [comment]
Thanks, Christina. You can make the call whether it lives on the GDrive or the Google Drive. Both are easily accessible to our team. I would be a little concerned about formatting issues in Google Drive so am leaning slightly toward the GDrive. You have the right of it though. We want to have only one copy of this where ever it lands!

**Comment by Conrathcl** [comment]
I deleted the google drive copy.  I am about to jump into working on the table of contents and I think that might be challenging on the google. Most of the things on my to do list have been checked off.  I think it is down to any additional edits, updating the personnel list, and fixing the toc.

**Comment by Conrathcl** [comment]
Hi All,  I'm done with all that I had planned for the document.  It would be good to get one last personnel update.  If there are any additional edits or substantial changes we should update the TOC again, but hopefully all of the formatting is done to make this a simple just push the update button exercise.  

Ned - let me know if there is anything else you want me to edit or add.  This is the point where I usually leave it in supervisory hands to finalize.

**Comment by Ned-Laman-NOAA** [comment]
Got it, and Thanks, Christina.
I will put this on the docket to review before the end of April. 
If I make any substantive changes I will run them by you to make sure I haven't messed something up down the line.

**Comment by Ned-Laman-NOAA** [comment]
I put the "final" edits into this document so it got "done" technically.
Turns out there are still a few things that needed to be fixed which are now in the digital copy and hand entered in the printed copies!
